/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class poi_demo_fmm_entity_renderer_ModelHuman_CustomModelRenderer */

#ifndef _Included_poi_demo_fmm_entity_renderer_ModelHuman_CustomModelRenderer
#define _Included_poi_demo_fmm_entity_renderer_ModelHuman_CustomModelRenderer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     poi_demo_fmm_entity_renderer_ModelHuman_CustomModelRenderer
 * Method:    renderCustomModel
 * Signature: (FFFFFFI)V
 */
JNIEXPORT void JNICALL Java_poi_demo_fmm_entity_renderer_ModelHuman_00024CustomModelRenderer_renderCustomModel
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jlong);

/*
 * Class:     poi_demo_fmm_entity_renderer_ModelHuman_CustomModelRenderer
 * Method:    loadCustomModel
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jlong JNICALL Java_poi_demo_fmm_entity_renderer_ModelHuman_00024CustomModelRenderer_loadCustomModel
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
