/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class poi_demo_fmm_entity_renderer_ModelHuman */

#ifndef _Included_poi_demo_fmm_entity_renderer_ModelHuman
#define _Included_poi_demo_fmm_entity_renderer_ModelHuman
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
