/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class poi_demo_fmm_entity_renderer_RenderHuman */

#ifndef _Included_poi_demo_fmm_entity_renderer_RenderHuman
#define _Included_poi_demo_fmm_entity_renderer_RenderHuman
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     poi_demo_fmm_entity_renderer_RenderHuman
 * Method:    doReneder
 * Signature: (DDDFF)V
 */
JNIEXPORT void JNICALL Java_poi_demo_fmm_entity_renderer_RenderHuman_doReneder
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
